# Generated by Django 3.2.13 on 2022-05-25 02:30

from django.db import migrations, models
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sensitive_data', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
            ],
        ),
    ]
